/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recieptsgen;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Eduardo
 */
public class RecieptsGenAcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form RecieptsGenAcercaDe
     */
    
    public RecieptsGenAcercaDe() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logonuevo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecieptsGenAcercaDeLabelTitulo = new javax.swing.JLabel();
        RecieptsGenAcercaDeLabelSubtitulo = new javax.swing.JLabel();
        RecieptsGenLogo = new javax.swing.JLabel();
        RecieptsGenAcercaDeLabelTexto1 = new javax.swing.JLabel();
        RecieptsGenAcercaDeLabelTexto2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de");

        RecieptsGenAcercaDeLabelTitulo.setFont(new java.awt.Font("Eras Bold ITC", 0, 28)); // NOI18N
        RecieptsGenAcercaDeLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecieptsGenAcercaDeLabelTitulo.setText("RecieptsGen");

        RecieptsGenAcercaDeLabelSubtitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RecieptsGenAcercaDeLabelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecieptsGenAcercaDeLabelSubtitulo.setText("Version Prototipo 0.2");

        RecieptsGenLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecieptsGenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logonuevo288.png"))); // NOI18N

        RecieptsGenAcercaDeLabelTexto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RecieptsGenAcercaDeLabelTexto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecieptsGenAcercaDeLabelTexto1.setText("Creado y programado por Eduardo Viñas Valdez");

        RecieptsGenAcercaDeLabelTexto2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RecieptsGenAcercaDeLabelTexto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecieptsGenAcercaDeLabelTexto2.setText("Universidad Politecnica de Tecamac / Ingenieria en software");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RecieptsGenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(RecieptsGenAcercaDeLabelSubtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(RecieptsGenAcercaDeLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RecieptsGenAcercaDeLabelTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(RecieptsGenAcercaDeLabelTexto2)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(RecieptsGenAcercaDeLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RecieptsGenAcercaDeLabelSubtitulo)
                .addGap(18, 18, 18)
                .addComponent(RecieptsGenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecieptsGenAcercaDeLabelTexto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RecieptsGenAcercaDeLabelTexto2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecieptsGenAcercaDe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RecieptsGenAcercaDeLabelSubtitulo;
    private javax.swing.JLabel RecieptsGenAcercaDeLabelTexto1;
    private javax.swing.JLabel RecieptsGenAcercaDeLabelTexto2;
    private javax.swing.JLabel RecieptsGenAcercaDeLabelTitulo;
    private javax.swing.JLabel RecieptsGenLogo;
    // End of variables declaration//GEN-END:variables
}
