/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recieptsgen;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;
/**
 *
 * @author Eduardo
 */
public class RecieptsGenFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form RecieptGenFramePrincipal
     */
    
    public RecieptsGenFramePrincipal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logonuevo.png")).getImage());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInicial = new javax.swing.JPanel();
        GrupoDatosDelAlumno = new javax.swing.JPanel();
        LabelMatricula = new javax.swing.JLabel();
        TextFieldAlumnos = new javax.swing.JTextField();
        LabelApellidos = new javax.swing.JLabel();
        TextFieldApellidos = new javax.swing.JTextField();
        LabelNombre1 = new javax.swing.JLabel();
        TextFieldMatricula = new javax.swing.JTextField();
        LabelCuatrimestre = new javax.swing.JLabel();
        TextFieldCuatrimestre = new javax.swing.JTextField();
        LabelGrupo = new javax.swing.JLabel();
        ComboBoxCarrera = new javax.swing.JComboBox<>();
        LabelCarrera = new javax.swing.JLabel();
        ComboBoxGrupo = new javax.swing.JComboBox<>();
        LabelGenero = new javax.swing.JLabel();
        CheckBoxFemenino = new javax.swing.JCheckBox();
        CheckBoxMasculino = new javax.swing.JCheckBox();
        CheckBoxOtro = new javax.swing.JCheckBox();
        LabelNacimiento = new javax.swing.JLabel();
        ComboBoxTurno = new javax.swing.JComboBox<>();
        LabelTurno = new javax.swing.JLabel();
        ButtonInsertar = new javax.swing.JButton();
        ButtonConfirmarDatosAlumno = new javax.swing.JButton();
        DateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        GrupoInformacionDelJustificante = new javax.swing.JPanel();
        LabelTurno1 = new javax.swing.JLabel();
        ComboBoxJustificacion = new javax.swing.JComboBox<>();
        LabelTurno2 = new javax.swing.JLabel();
        ComboBoxFormatoVisual = new javax.swing.JComboBox<>();
        LabelTurno3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTextoMotivos = new javax.swing.JTextArea();
        ButtonPreferenciasJustificante = new javax.swing.JButton();
        ButtonConfirmarInformacionJustificante = new javax.swing.JButton();
        ButtonPreferenciasPrincipal = new javax.swing.JButton();
        ButtonConfirmarPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RecieptsGen");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        GrupoDatosDelAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos del alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        GrupoDatosDelAlumno.setName(""); // NOI18N

        LabelMatricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelMatricula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelMatricula.setText("Matricula");

        TextFieldAlumnos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextFieldAlumnos.setBorder(null);
        TextFieldAlumnos.setMinimumSize(new java.awt.Dimension(64, 21));

        LabelApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelApellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelApellidos.setText("Apellidos (s)");

        TextFieldApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextFieldApellidos.setBorder(null);
        TextFieldApellidos.setMinimumSize(new java.awt.Dimension(64, 21));

        LabelNombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNombre1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelNombre1.setText("Nombre (s)");

        TextFieldMatricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextFieldMatricula.setBorder(null);

        LabelCuatrimestre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCuatrimestre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelCuatrimestre.setText("Cuatrimestre");

        TextFieldCuatrimestre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextFieldCuatrimestre.setBorder(null);

        LabelGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelGrupo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelGrupo.setText("Grupo");

        ComboBoxCarrera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Licenciatura en Negocios Internacionales", "Ingeniería en Mecánica Automotriz", "Ingeniería en Software", "Ingeniería en Tecnologías de Manufactura", "Ingeniería Financiera" }));
        ComboBoxCarrera.setBorder(null);

        LabelCarrera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCarrera.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelCarrera.setText("Carrera");

        ComboBoxGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "6122IMA", "7122IMA", "2422IMA", "5422IMA", "1722IMA", "3322IS", "2422IS", "3422IS", "2722IS", "1122ITM", "1422ITM", "2422ITM" }));
        ComboBoxGrupo.setBorder(null);

        LabelGenero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelGenero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelGenero.setText("Genero");

        CheckBoxFemenino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBoxFemenino.setText("Femenino");

        CheckBoxMasculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBoxMasculino.setText("Masculino");

        CheckBoxOtro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBoxOtro.setText("Otro");

        LabelNacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelNacimiento.setText("Fecha de nacimiento");

        ComboBoxTurno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Matutino", "Vespertino" }));
        ComboBoxTurno.setBorder(null);

        LabelTurno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTurno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTurno.setText("Turno");

        ButtonInsertar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonInsertar.setText("Insertar desde base de datos");
        ButtonInsertar.setBorder(null);
        ButtonInsertar.setPreferredSize(new java.awt.Dimension(185, 28));
        ButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInsertarActionPerformed(evt);
            }
        });

        ButtonConfirmarDatosAlumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonConfirmarDatosAlumno.setText("Confirmar");
        ButtonConfirmarDatosAlumno.setBorder(null);
        ButtonConfirmarDatosAlumno.setPreferredSize(new java.awt.Dimension(64, 28));
        ButtonConfirmarDatosAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmarDatosAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GrupoDatosDelAlumnoLayout = new javax.swing.GroupLayout(GrupoDatosDelAlumno);
        GrupoDatosDelAlumno.setLayout(GrupoDatosDelAlumnoLayout);
        GrupoDatosDelAlumnoLayout.setHorizontalGroup(
            GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                        .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelNombre1)
                            .addComponent(LabelMatricula)
                            .addComponent(LabelCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextFieldMatricula)
                            .addComponent(ComboBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                                .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GrupoDatosDelAlumnoLayout.createSequentialGroup()
                                .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelApellidos)
                                    .addComponent(LabelCuatrimestre)
                                    .addComponent(TextFieldApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldCuatrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(LabelGenero))
                                    .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CheckBoxOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(CheckBoxMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CheckBoxFemenino)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelNacimiento)
                                    .addComponent(ComboBoxTurno, 0, 200, Short.MAX_VALUE)
                                    .addComponent(LabelTurno)
                                    .addComponent(DateFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonConfirmarDatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        GrupoDatosDelAlumnoLayout.setVerticalGroup(
            GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelApellidos)
                    .addComponent(LabelNombre1)
                    .addComponent(LabelGenero)
                    .addComponent(LabelNacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                        .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckBoxFemenino)
                            .addComponent(TextFieldAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelMatricula)
                                .addComponent(LabelCuatrimestre))
                            .addComponent(CheckBoxMasculino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                                .addComponent(CheckBoxOtro)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TextFieldMatricula)
                            .addComponent(TextFieldCuatrimestre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelGrupo)
                            .addComponent(LabelCarrera))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GrupoDatosDelAlumnoLayout.createSequentialGroup()
                        .addComponent(DateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46)
                .addGroup(GrupoDatosDelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConfirmarDatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        GrupoInformacionDelJustificante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion del justificante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        LabelTurno1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTurno1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTurno1.setText("Tipo de justificacion");

        ComboBoxJustificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxJustificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Medica", "Estudiantil" }));
        ComboBoxJustificacion.setToolTipText("");
        ComboBoxJustificacion.setBorder(null);

        LabelTurno2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTurno2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTurno2.setText("Tipo de formato visual");

        ComboBoxFormatoVisual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxFormatoVisual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Item 2", "Item 3", "Item 4" }));
        ComboBoxFormatoVisual.setBorder(null);

        LabelTurno3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTurno3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTurno3.setText("Motivos");

        AreaTextoMotivos.setColumns(20);
        AreaTextoMotivos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AreaTextoMotivos.setRows(5);
        AreaTextoMotivos.setBorder(null);
        jScrollPane1.setViewportView(AreaTextoMotivos);

        ButtonPreferenciasJustificante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonPreferenciasJustificante.setText("Preferencias");
        ButtonPreferenciasJustificante.setBorder(null);
        ButtonPreferenciasJustificante.setPreferredSize(new java.awt.Dimension(77, 28));
        ButtonPreferenciasJustificante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPreferenciasJustificanteActionPerformed(evt);
            }
        });

        ButtonConfirmarInformacionJustificante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonConfirmarInformacionJustificante.setText("Confirmar");
        ButtonConfirmarInformacionJustificante.setBorder(null);
        ButtonConfirmarInformacionJustificante.setPreferredSize(new java.awt.Dimension(64, 28));
        ButtonConfirmarInformacionJustificante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmarInformacionJustificanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GrupoInformacionDelJustificanteLayout = new javax.swing.GroupLayout(GrupoInformacionDelJustificante);
        GrupoInformacionDelJustificante.setLayout(GrupoInformacionDelJustificanteLayout);
        GrupoInformacionDelJustificanteLayout.setHorizontalGroup(
            GrupoInformacionDelJustificanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrupoInformacionDelJustificanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GrupoInformacionDelJustificanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelTurno1)
                    .addComponent(ComboBoxJustificacion, 0, 200, Short.MAX_VALUE)
                    .addComponent(LabelTurno2)
                    .addComponent(ComboBoxFormatoVisual, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(GrupoInformacionDelJustificanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GrupoInformacionDelJustificanteLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(LabelTurno3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GrupoInformacionDelJustificanteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GrupoInformacionDelJustificanteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonPreferenciasJustificante, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConfirmarInformacionJustificante, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        GrupoInformacionDelJustificanteLayout.setVerticalGroup(
            GrupoInformacionDelJustificanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrupoInformacionDelJustificanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GrupoInformacionDelJustificanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTurno1)
                    .addComponent(LabelTurno3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GrupoInformacionDelJustificanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GrupoInformacionDelJustificanteLayout.createSequentialGroup()
                        .addComponent(ComboBoxJustificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTurno2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxFormatoVisual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GrupoInformacionDelJustificanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonConfirmarInformacionJustificante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPreferenciasJustificante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ButtonPreferenciasPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonPreferenciasPrincipal.setText("Preferencias");
        ButtonPreferenciasPrincipal.setBorder(null);
        ButtonPreferenciasPrincipal.setPreferredSize(new java.awt.Dimension(77, 28));
        ButtonPreferenciasPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPreferenciasPrincipalActionPerformed(evt);
            }
        });

        ButtonConfirmarPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonConfirmarPrincipal.setText("Confirmar");
        ButtonConfirmarPrincipal.setBorder(null);
        ButtonConfirmarPrincipal.setPreferredSize(new java.awt.Dimension(64, 28));
        ButtonConfirmarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmarPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInicialLayout = new javax.swing.GroupLayout(PanelInicial);
        PanelInicial.setLayout(PanelInicialLayout);
        PanelInicialLayout.setHorizontalGroup(
            PanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GrupoDatosDelAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GrupoInformacionDelJustificante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonPreferenciasPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConfirmarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        PanelInicialLayout.setVerticalGroup(
            PanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GrupoDatosDelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrupoInformacionDelJustificante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPreferenciasPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConfirmarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInsertarActionPerformed
        RecieptsGenFrameBaseDatos RGFrameBaseDatos = new RecieptsGenFrameBaseDatos();
        RGFrameBaseDatos.setVisible(true);
    }//GEN-LAST:event_ButtonInsertarActionPerformed

    private void ButtonPreferenciasPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPreferenciasPrincipalActionPerformed
        RecieptsGenPreferenciasGeneral RGPreferenciasGeneral = new RecieptsGenPreferenciasGeneral();
        RGPreferenciasGeneral.setVisible(true);
    }//GEN-LAST:event_ButtonPreferenciasPrincipalActionPerformed

    private void ButtonPreferenciasJustificanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPreferenciasJustificanteActionPerformed
        RecieptsGenPreferenciasJustificante RGPreferenciasJustificante = new RecieptsGenPreferenciasJustificante();
        RGPreferenciasJustificante.setVisible(true);
    }//GEN-LAST:event_ButtonPreferenciasJustificanteActionPerformed

    private void ButtonConfirmarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmarPrincipalActionPerformed
        RecieptsGenFrameJustificanteGenerado RGJustificanteGenerado = new RecieptsGenFrameJustificanteGenerado();
        RGJustificanteGenerado.setVisible(true);
    }//GEN-LAST:event_ButtonConfirmarPrincipalActionPerformed

    private void ButtonConfirmarDatosAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmarDatosAlumnoActionPerformed
        if (TextFieldAlumnos.getText().isEmpty() || TextFieldApellidos.getText().isEmpty() || TextFieldMatricula.getText().isEmpty() || TextFieldCuatrimestre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dejo uno o mas espacios vacios.");
        }
        else
        {
            try {
            BufferedWriter Escribir = new BufferedWriter(new FileWriter("RGTempAlumno00.txt"));
            
            Escribir.write("RecieptsGen.\n");
            Escribir.write("Por EViasValdez\n");
            Escribir.write("V. Prototipo 0.1\n");
            Escribir.write("• • • • • • • • • • • • • • • • • • • • • • • • • • • •\n");
            Escribir.write("\n");
            Escribir.write("Reporte de generacion de justificante sin finalizar\n");
            Escribir.write("Motivo - Cierre de programa \n");
            Escribir.write("00/00/00 00:00 \n");
            Escribir.write("\n");
            Escribir.write("|||| Datos del alumno ||||\n");
            Escribir.write("Nombres - " + TextFieldAlumnos.getText() + "\n");
            Escribir.write("Apellidos - " + TextFieldApellidos.getText() + "\n");
            Escribir.write("Matricula - " + TextFieldMatricula.getText() + "\n");
            Escribir.write("Cuatrimestre - " + TextFieldCuatrimestre.getText() + "\n");
            Escribir.write("Carrera - " + ComboBoxCarrera.getSelectedItem() + "\n");
            Escribir.write("Grupo - " + ComboBoxGrupo.getSelectedItem() + "\n");
            Escribir.write("Genero - " + CheckBoxFemenino.getActionCommand() + "\n");
            Escribir.write("Genero - " + CheckBoxMasculino.getActionCommand() + "\n");
            Escribir.write("Genero - " + CheckBoxOtro.getActionCommand() + "\n");
            Escribir.write("Turno - " + ComboBoxTurno.getSelectedItem() + "\n");
            Escribir.close();
         }catch(Exception ex){
            ex.printStackTrace();
         }
            JOptionPane.showMessageDialog(this, "La informacion ha sido confirmada.");
        }
    }//GEN-LAST:event_ButtonConfirmarDatosAlumnoActionPerformed

    private void ButtonConfirmarInformacionJustificanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmarInformacionJustificanteActionPerformed
        if (AreaTextoMotivos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dejo uno o mas espacios vacios.");
        }
        else
        {
            try {
                BufferedWriter Escribir = new BufferedWriter(new FileWriter("RGTempJustificante00.txt"));
                Escribir.write("RecieptsGen.\n");
                Escribir.write("Por EViasValdez\n");
                Escribir.write("V. Prototipo 0.1\n");
                Escribir.write("• • • • • • • • • • • • • • • • • • • • • • • • • • • •\n");
                Escribir.write("\n");
                Escribir.write("Reporte de generacion de justificante sin finalizar\n");
                Escribir.write("Motivo - Cierre de programa \n");
                Escribir.write("00/00/00 00:00 \n");
                Escribir.write("\n");
                Escribir.write("|||| Informacion del justificante ||||\n");
                Escribir.write("Tipo de justificacion - " + ComboBoxJustificacion.getSelectedItem() + "\n");
                Escribir.write("Tipo de formato visual - " + ComboBoxFormatoVisual.getSelectedItem() + "\n");
                Escribir.write("Motivos - " + AreaTextoMotivos.getText() + "\n");
                Escribir.close();
                
            } catch (IOException ex) {
                Logger.getLogger(RecieptsGenFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "La informacion ha sido confirmada.");
            
        }
    }//GEN-LAST:event_ButtonConfirmarInformacionJustificanteActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new MetalLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(RecieptsGenFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    Thread.sleep(4000);
                } catch(Exception e) {
		
                }
                
                new RecieptsGenFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTextoMotivos;
    private javax.swing.JButton ButtonConfirmarDatosAlumno;
    private javax.swing.JButton ButtonConfirmarInformacionJustificante;
    private javax.swing.JButton ButtonConfirmarPrincipal;
    private javax.swing.JButton ButtonInsertar;
    private javax.swing.JButton ButtonPreferenciasJustificante;
    private javax.swing.JButton ButtonPreferenciasPrincipal;
    private javax.swing.JCheckBox CheckBoxFemenino;
    private javax.swing.JCheckBox CheckBoxMasculino;
    private javax.swing.JCheckBox CheckBoxOtro;
    private javax.swing.JComboBox<String> ComboBoxCarrera;
    private javax.swing.JComboBox<String> ComboBoxFormatoVisual;
    private javax.swing.JComboBox<String> ComboBoxGrupo;
    private javax.swing.JComboBox<String> ComboBoxJustificacion;
    private javax.swing.JComboBox<String> ComboBoxTurno;
    private com.toedter.calendar.JDateChooser DateFechaNacimiento;
    private javax.swing.JPanel GrupoDatosDelAlumno;
    private javax.swing.JPanel GrupoInformacionDelJustificante;
    private javax.swing.JLabel LabelApellidos;
    private javax.swing.JLabel LabelCarrera;
    private javax.swing.JLabel LabelCuatrimestre;
    private javax.swing.JLabel LabelGenero;
    private javax.swing.JLabel LabelGrupo;
    private javax.swing.JLabel LabelMatricula;
    private javax.swing.JLabel LabelNacimiento;
    private javax.swing.JLabel LabelNombre1;
    private javax.swing.JLabel LabelTurno;
    private javax.swing.JLabel LabelTurno1;
    private javax.swing.JLabel LabelTurno2;
    private javax.swing.JLabel LabelTurno3;
    private javax.swing.JPanel PanelInicial;
    private javax.swing.JTextField TextFieldAlumnos;
    private javax.swing.JTextField TextFieldApellidos;
    private javax.swing.JTextField TextFieldCuatrimestre;
    private javax.swing.JTextField TextFieldMatricula;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
