/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recieptsgen;

import javax.swing.ImageIcon;

/**
 *
 * @author Eduardo
 */
public class RecieptsGenPreferenciasGeneral extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public RecieptsGenPreferenciasGeneral() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logonuevo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FramePreferenciasGeneral = new javax.swing.JPanel();
        PanelOpcionesGeneral = new javax.swing.JPanel();
        LabelColor = new javax.swing.JLabel();
        LabelIdioma = new javax.swing.JLabel();
        LabelFormato = new javax.swing.JLabel();
        ComboBoxColorAplicacion = new javax.swing.JComboBox<>();
        ComboBoxIdioma = new javax.swing.JComboBox<>();
        ComboBoxFormatoVisualizacion = new javax.swing.JComboBox<>();
        CheckBoxAutoguardado = new javax.swing.JCheckBox();
        LabelImpresion = new javax.swing.JLabel();
        ButtonRevisarAjustes = new javax.swing.JButton();
        ButtonImprimirHojaPrueba = new javax.swing.JButton();
        CheckBoxCorregirErrores = new javax.swing.JCheckBox();
        PanelOpcionesBaseDatos = new javax.swing.JPanel();
        LabelBaseDatos = new javax.swing.JLabel();
        ButtonActualizar = new javax.swing.JButton();
        ButtonVerificarConexion = new javax.swing.JButton();
        ButtonModificarDatos = new javax.swing.JButton();
        ButtonAdministrarDatos = new javax.swing.JButton();
        LabelFormatoSQL = new javax.swing.JLabel();
        ComboBoxFormatoSQL = new javax.swing.JComboBox<>();
        LabelGestorSQL = new javax.swing.JLabel();
        ComboBoxGestorSQL = new javax.swing.JComboBox<>();
        LabelVerificarConexion = new javax.swing.JLabel();
        ComboBoxVerificarConexion = new javax.swing.JComboBox<>();
        ButtonAbrirGestor = new javax.swing.JButton();
        ButtonVerBaseDatos = new javax.swing.JButton();
        ButtonAceptar = new javax.swing.JButton();
        ButtonAplicar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();
        ButtonAcercaDe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones");

        PanelOpcionesGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones en general", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        LabelColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelColor.setText("Color de la aplicacion");

        LabelIdioma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelIdioma.setText("Idioma");

        LabelFormato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelFormato.setText("Formato predeterminado de visualizacion");

        ComboBoxColorAplicacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxColorAplicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Predeterminado del sistema", "Claro", "Obscuro" }));

        ComboBoxIdioma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Predeterminado del sistema" }));

        ComboBoxFormatoVisualizacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxFormatoVisualizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "PNG" }));

        CheckBoxAutoguardado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBoxAutoguardado.setText("Autoguardado");

        LabelImpresion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelImpresion.setText("Formato de impresion");

        ButtonRevisarAjustes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonRevisarAjustes.setText("Revisar ajustes");

        ButtonImprimirHojaPrueba.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonImprimirHojaPrueba.setText("Imprimir hoja de prueba");

        CheckBoxCorregirErrores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBoxCorregirErrores.setText("Corregir errores ortograficos");

        javax.swing.GroupLayout PanelOpcionesGeneralLayout = new javax.swing.GroupLayout(PanelOpcionesGeneral);
        PanelOpcionesGeneral.setLayout(PanelOpcionesGeneralLayout);
        PanelOpcionesGeneralLayout.setHorizontalGroup(
            PanelOpcionesGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOpcionesGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelFormato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxColorAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxFormatoVisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonRevisarAjustes)
                    .addComponent(ButtonImprimirHojaPrueba)
                    .addComponent(LabelImpresion)
                    .addComponent(CheckBoxCorregirErrores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CheckBoxAutoguardado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelOpcionesGeneralLayout.setVerticalGroup(
            PanelOpcionesGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxColorAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(LabelIdioma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelFormato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxFormatoVisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBoxAutoguardado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelImpresion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonRevisarAjustes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonImprimirHojaPrueba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBoxCorregirErrores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelOpcionesBaseDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de base de datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        LabelBaseDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelBaseDatos.setText("Base de datos");

        ButtonActualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonActualizar.setText("Actualizar");

        ButtonVerificarConexion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonVerificarConexion.setText("Verificar conexion");

        ButtonModificarDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonModificarDatos.setText("Modificar datos");

        ButtonAdministrarDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonAdministrarDatos.setText("Administrar datos");

        LabelFormatoSQL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelFormatoSQL.setText("Formato SQL");

        ComboBoxFormatoSQL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxFormatoSQL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MySQL" }));

        LabelGestorSQL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelGestorSQL.setText("Gestor SQL");

        ComboBoxGestorSQL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxGestorSQL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WAMPP", "XAMPP" }));

        LabelVerificarConexion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelVerificarConexion.setText("Verificar conexion antes de crear jutificante");

        ComboBoxVerificarConexion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBoxVerificarConexion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        ButtonAbrirGestor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonAbrirGestor.setText("Abrir gestor");

        ButtonVerBaseDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonVerBaseDatos.setText("Ver base de datos");

        javax.swing.GroupLayout PanelOpcionesBaseDatosLayout = new javax.swing.GroupLayout(PanelOpcionesBaseDatos);
        PanelOpcionesBaseDatos.setLayout(PanelOpcionesBaseDatosLayout);
        PanelOpcionesBaseDatosLayout.setHorizontalGroup(
            PanelOpcionesBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesBaseDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOpcionesBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelBaseDatos)
                    .addComponent(LabelFormatoSQL)
                    .addComponent(LabelGestorSQL)
                    .addComponent(LabelVerificarConexion)
                    .addGroup(PanelOpcionesBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ButtonActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAdministrarDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonModificarDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonVerificarConexion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addGroup(PanelOpcionesBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ComboBoxGestorSQL, javax.swing.GroupLayout.Alignment.LEADING, 0, 140, Short.MAX_VALUE)
                        .addComponent(ComboBoxFormatoSQL, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ComboBoxVerificarConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelOpcionesBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ButtonAbrirGestor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonVerBaseDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PanelOpcionesBaseDatosLayout.setVerticalGroup(
            PanelOpcionesBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesBaseDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBaseDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonVerificarConexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonModificarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonAdministrarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelFormatoSQL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxFormatoSQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelGestorSQL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxGestorSQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelVerificarConexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxVerificarConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonAbrirGestor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ButtonVerBaseDatos)
                .addContainerGap())
        );

        ButtonAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonAceptar.setText("Aceptar");

        ButtonAplicar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonAplicar.setText("Aplicar");

        ButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonAcercaDe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonAcercaDe.setText("Acerca de");
        ButtonAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAcercaDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FramePreferenciasGeneralLayout = new javax.swing.GroupLayout(FramePreferenciasGeneral);
        FramePreferenciasGeneral.setLayout(FramePreferenciasGeneralLayout);
        FramePreferenciasGeneralLayout.setHorizontalGroup(
            FramePreferenciasGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramePreferenciasGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FramePreferenciasGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FramePreferenciasGeneralLayout.createSequentialGroup()
                        .addComponent(ButtonAcercaDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonAplicar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonAceptar))
                    .addGroup(FramePreferenciasGeneralLayout.createSequentialGroup()
                        .addComponent(PanelOpcionesGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelOpcionesBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FramePreferenciasGeneralLayout.setVerticalGroup(
            FramePreferenciasGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramePreferenciasGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FramePreferenciasGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOpcionesGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelOpcionesBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FramePreferenciasGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonAcercaDe, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(ButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FramePreferenciasGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FramePreferenciasGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAcercaDeActionPerformed
        RecieptsGenAcercaDe RGAcercaDe = new RecieptsGenAcercaDe();
        RGAcercaDe.setVisible(true);
    }//GEN-LAST:event_ButtonAcercaDeActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenPreferenciasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenPreferenciasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenPreferenciasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenPreferenciasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecieptsGenPreferenciasGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAbrirGestor;
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JButton ButtonAcercaDe;
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonAdministrarDatos;
    private javax.swing.JButton ButtonAplicar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonImprimirHojaPrueba;
    private javax.swing.JButton ButtonModificarDatos;
    private javax.swing.JButton ButtonRevisarAjustes;
    private javax.swing.JButton ButtonVerBaseDatos;
    private javax.swing.JButton ButtonVerificarConexion;
    private javax.swing.JCheckBox CheckBoxAutoguardado;
    private javax.swing.JCheckBox CheckBoxCorregirErrores;
    private javax.swing.JComboBox<String> ComboBoxColorAplicacion;
    private javax.swing.JComboBox<String> ComboBoxFormatoSQL;
    private javax.swing.JComboBox<String> ComboBoxFormatoVisualizacion;
    private javax.swing.JComboBox<String> ComboBoxGestorSQL;
    private javax.swing.JComboBox<String> ComboBoxIdioma;
    private javax.swing.JComboBox<String> ComboBoxVerificarConexion;
    private javax.swing.JPanel FramePreferenciasGeneral;
    private javax.swing.JLabel LabelBaseDatos;
    private javax.swing.JLabel LabelColor;
    private javax.swing.JLabel LabelFormato;
    private javax.swing.JLabel LabelFormatoSQL;
    private javax.swing.JLabel LabelGestorSQL;
    private javax.swing.JLabel LabelIdioma;
    private javax.swing.JLabel LabelImpresion;
    private javax.swing.JLabel LabelVerificarConexion;
    private javax.swing.JPanel PanelOpcionesBaseDatos;
    private javax.swing.JPanel PanelOpcionesGeneral;
    // End of variables declaration//GEN-END:variables
}