/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recieptsgen;

import javax.swing.ImageIcon;

/**
 *
 * @author Eduardo
 */
public class RecieptsGenFrameJustificanteGenerado extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public RecieptsGenFrameJustificanteGenerado() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logonuevo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelJusticante = new javax.swing.JPanel();
        FrameJustificanteGenerado = new javax.swing.JPanel();
        PanelJustificanteGenerado = new javax.swing.JPanel();
        LabelJustificante1 = new javax.swing.JLabel();
        ButtonVistaPrevia = new javax.swing.JButton();
        ButtonImprimir = new javax.swing.JButton();
        ButtonGuardar = new javax.swing.JButton();

        setTitle("Justificante generado");

        PanelJustificanteGenerado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Justificante generado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        LabelJustificante1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelJustificante1.setText("Listo, el justificante ha sido generado, de click en el boton \"ver vista previa\" para poder verlo.");

        ButtonVistaPrevia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonVistaPrevia.setText("Ver vista previa");

        javax.swing.GroupLayout PanelJustificanteGeneradoLayout = new javax.swing.GroupLayout(PanelJustificanteGenerado);
        PanelJustificanteGenerado.setLayout(PanelJustificanteGeneradoLayout);
        PanelJustificanteGeneradoLayout.setHorizontalGroup(
            PanelJustificanteGeneradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJustificanteGeneradoLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(PanelJustificanteGeneradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJustificanteGeneradoLayout.createSequentialGroup()
                        .addComponent(LabelJustificante1)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJustificanteGeneradoLayout.createSequentialGroup()
                        .addComponent(ButtonVistaPrevia)
                        .addGap(334, 334, 334))))
        );
        PanelJustificanteGeneradoLayout.setVerticalGroup(
            PanelJustificanteGeneradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJustificanteGeneradoLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(ButtonVistaPrevia)
                .addGap(63, 63, 63)
                .addComponent(LabelJustificante1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        ButtonImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonImprimir.setText("Imprimir");

        ButtonGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonGuardar.setText("Guardar");

        javax.swing.GroupLayout FrameJustificanteGeneradoLayout = new javax.swing.GroupLayout(FrameJustificanteGenerado);
        FrameJustificanteGenerado.setLayout(FrameJustificanteGeneradoLayout);
        FrameJustificanteGeneradoLayout.setHorizontalGroup(
            FrameJustificanteGeneradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameJustificanteGeneradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelJustificanteGenerado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameJustificanteGeneradoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonGuardar)
                .addContainerGap())
        );
        FrameJustificanteGeneradoLayout.setVerticalGroup(
            FrameJustificanteGeneradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameJustificanteGeneradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelJustificanteGenerado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameJustificanteGeneradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelJusticanteLayout = new javax.swing.GroupLayout(PanelJusticante);
        PanelJusticante.setLayout(PanelJusticanteLayout);
        PanelJusticanteLayout.setHorizontalGroup(
            PanelJusticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameJustificanteGenerado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelJusticanteLayout.setVerticalGroup(
            PanelJusticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJusticanteLayout.createSequentialGroup()
                .addComponent(FrameJustificanteGenerado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelJusticante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelJusticante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenFrameJustificanteGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenFrameJustificanteGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenFrameJustificanteGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecieptsGenFrameJustificanteGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecieptsGenFrameJustificanteGenerado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JButton ButtonImprimir;
    private javax.swing.JButton ButtonVistaPrevia;
    private javax.swing.JPanel FrameJustificanteGenerado;
    private javax.swing.JLabel LabelJustificante1;
    private javax.swing.JPanel PanelJusticante;
    private javax.swing.JPanel PanelJustificanteGenerado;
    // End of variables declaration//GEN-END:variables
}